name: Run tests on different OS
on: [workflow_dispatch, workflow_call]
jobs:
  os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15-intel, macos-15]
        shell: [bash]
        include:
          - os: windows-2022
            shell: 'msys2 {0}'
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      PYTEST_ADDOPTS: --verbose --hypothesis-profile=default
      CFLAGS: -Wall -Wpedantic -Werror -std=c17 -Wconversion
      MACOSX_DEPLOYMENT_TARGET: 10.15  # for 3.14
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: msys2/setup-msys2@v2.29.0
        with:
          install: >-
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-gcc
            diffutils
            m4
            make
            patch
          msystem: ucrt64
          path-type: inherit
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Cache GNU GMP builds
        id: cache-gmp
        uses: actions/cache@v4
        with:
          path: .local
          key: ${{ matrix.os }}-${{ hashFiles('scripts/*') }}
      - run: bash scripts/cibw_before_all.sh
        if: steps.cache-gmp.outputs.cache-hit != 'true'
      - run: python -m pip install --upgrade pip
      - run: |
          # XXX: this is for M$ Windows, see msys2/setup-msys2#171
          PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:$(pwd)/.local/lib/pkgconfig
          pip --verbose wheel . -Csetup-args=-Dbuildtype=debug
      - run: |
          # XXX: this is too, see
          # https://mesonbuild.com/meson-python/how-to-guides/shared-libraries
          PATH="$PATH:$(pwd)/.local/bin"
          pip install delvewheel
          delvewheel repair *.whl
          mv wheelhouse/*.whl .
        if: ${{ startsWith(matrix.os, 'windows') }}
      - run: |
          pip install --verbose *.whl
          pip install --verbose python-gmp[tests]
      - run: pytest
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
