name: Run tests on different OS
on: [workflow_dispatch, workflow_call]
jobs:
  os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15-intel, macos-15]
        shell: [bash]
        msystem: [ucrt64]
        menv: [ucrt-x86_64]
        include:
          - os: windows-2022
            shell: 'msys2 {0}'
            msystem: ucrt64
            menv: ucrt-x86_64
          - os: windows-11-arm
            shell: 'msys2 {0}'
            msystem: clangarm64
            menv: clang-aarch64
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      PYTEST_ADDOPTS: --verbose --hypothesis-profile=default
#     CFLAGS: -Wall -Wpedantic -Werror -std=c17 -Wconversion
      MACOSX_DEPLOYMENT_TARGET: 10.15  # for 3.14
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: msys2/setup-msys2@v2.29.0
        with:
          install: >-
            mingw-w64-${{ matrix.menv }}-binutils
            mingw-w64-${{ matrix.menv }}-gcc
            mingw-w64-${{ matrix.menv }}-pkg-config
            mingw-w64-${{ matrix.menv }}-tools
            diffutils
            m4
            make
            patch
            autotools
          msystem: ${{ matrix.msystem }}
          path-type: inherit
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Cache GNU GMP builds
        id: cache-gmp
        uses: actions/cache@v4
        with:
          path: .local
          key: ${{ matrix.os }}-${{ hashFiles('scripts/*') }}
      - run: sh scripts/cibw_before_all.sh
        if: steps.cache-gmp.outputs.cache-hit != 'true'
      - run: |
          export PKG_CONFIG_PATH=$(pwd)/.local/lib/pkgconfig
          pip --verbose wheel . -Csetup-args=-Dbuildtype=debug -Csetup-args=--vsenv
      # https://mesonbuild.com/meson-python/how-to-guides/shared-libraries
      - run: |
          pip install delvewheel
          delvewheel repair *.whl --add-path .local/bin
          mv wheelhouse/*.whl .
        if: ${{ startsWith(matrix.os, 'windows') }}
      - run: |
          pip install --verbose *.whl
          pip install --verbose python-gmp[tests]
      - run: pytest
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
